AWSTemplateFormatVersion: '2010-09-09'
Description: 'RGIT ERP MVP: Free Tier RDS Postgres & Lambda Backend'

Parameters:
  DBPassword:
    Type: String
    NoEcho: true
    Description: "Enter a strong password for the database"
    MinLength: 8

Resources:
  # 1. THE DATABASE (Using Postgres 15.4 for maximum compatibility)
  MyPostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: rgit-erp-db
      Engine: postgres
      EngineVersion: "15.4"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: postgres
      MasterUserPassword: !Ref DBPassword
      DBName: rgit_erp
      PubliclyAccessible: true
      StorageType: gp2
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - !Ref DBSecurityGroup

  # 2. SECURITY GROUP
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow connection to Postgres"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  # 3. LAMBDA ROLE
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # 4. THE BACKEND
  MyBackendFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: rgit-erp-api
      Handler: dist/index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs20.x
      Timeout: 15
      MemorySize: 128
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return { statusCode: 200, body: 'Backend is Live!' };
          };
      Environment:
        Variables:
          DATABASE_URL: !Sub "postgresql://postgres:${DBPassword}@${MyPostgresDB.Endpoint.Address}:5432/rgit_erp"

Outputs:
  DatabaseEndpoint:
    Description: "Connect to this URL in your Drizzle config"
    Value: !GetAtt MyPostgresDB.Endpoint.Address
  LambdaName:
    Description: "Lambda Function Name"
    Value: !Ref MyBackendFunction
